import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

//create initial states of variables as an object
const initialState = {
  data: {},
  dataPerPages: 1,
  currentPage: 1,
  loading: true,
  error: '',
};

/*to handle asyn data use thunk and perform asynchronous logic and dispatch regular synchronous 
actions with the fetched data from external api*/
export const fetchData = createAsyncThunk('fetchData', async () => {
  try {
    //get data from external api
    const res = await fetch('https://rickandmortyapi.com/api/character/');

    //extracting the JSON data from the response and assign data which came from external api to an object variable
    const data = await res.json();
    if (data) {
      return data;
    } else {
      return { err: 'some error' };
    }
  } catch (error) {
    return { err: 'some error' };
  }
});

/*createSlice is a higher-order function that accepts the slice name a set of reducers, and returns a 
single reducer along with the action creators for that reducer.*/
const getDataSlice = createSlice({
  name: 'get-data-slice',
  initialState,
  reducers: {
    //reducer for click and go to next page in pagination
    onNavigateNext: (state, action) => {
      state.currentPage++;
    },
    //reducer for click and go to previous page in pagination
    onNavigatePrev: (state, action) => {
      state.currentPage--;
    },
    //reducer for click change the data per page in pagination
    onChangeDataPerPage: (state, action) => {
      state.dataPerPages = action.payload;
    },
    //reducer for click and go to page what we want in pagination
    onClickCurrentPage: (state, action) => {
      state.currentPage = action.payload;
    },
  },
  //extraReducers allows you to define additional reducers that respond to actions generated by createAsyncThunk
  extraReducers: (builder) => {
    builder.addCase(fetchData.pending, (state, action) => {
      state.loading = true;
    });

    builder.addCase(fetchData.fulfilled, (state, action) => {
      state.data = action.payload;
      state.loading = false;
      state.error = '';
    });

    builder.addCase(fetchData.rejected, (state, action) => {
      state.error = action.payload;
      state.loading = true;
    });
  },
});

export const Actions = getDataSlice.actions;
export default getDataSlice.reducer;
